export const themes = [
  'Theme I: Learning-Teaching',
  'Theme II: Research & Technology Transfer',
  'Theme III: Community Engagement',
  'Theme IV: Good Governance',
];

export const kpiList = [
  {
    id: '1',
    no: '1.1.1',
    kpi: 'Percent of undergraduate students enrollment in all modalities',
    theme: 'Theme I: Learning-Teaching',
    subTheme: 'Access and Equity',
    unit: '%',
    weight: 1,
    baseline: '83.14%',
    target: '90.6%',
    remark: 'AVP & All Institutes',
  },
  {
    id: '2',
    no: '1.1.2',
    kpi: 'Percent of UG female students enrolled in the university',
    theme: 'Theme I: Learning-Teaching',
    subTheme: 'Access and Equity',
    unit: '%',
    weight: 0.5,
    baseline: '31.9',
    target: '35',
    remark: '',
  },
  {
    id: '3',
    no: '1.1.3',
    kpi: 'Increased percent of PG students enrollment',
    theme: 'Theme I: Learning-Teaching',
    subTheme: 'Access and Equity',
    unit: '%',
    weight: 1,
    baseline: '10',
    target: '15',
    remark: '',
  },
  {
    id: '4',
    no: '1.1.4',
    kpi: 'Number of academic programs provided using online modality',
    theme: 'Theme I: Learning-Teaching',
    subTheme: 'Access and Equity',
    unit: '#',
    weight: 1.5,
    baseline: '0',
    target: '2',
    remark: '',
  },
  {
    id: '5',
    no: '1.1.5',
    kpi: 'Number of academic programs provided using hybrid modality',
    theme: 'Theme I: Learning-Teaching',
    subTheme: 'Access and Equity',
    unit: '#',
    weight: 1,
    baseline: '13',
    target: '20',
    remark: '',
  },
  {
    id: '6',
    no: '1.2.1',
    kpi: 'Percent of first year UG students retained from preceding year',
    theme: 'Theme I: Learning-Teaching',
    subTheme: 'Efficiency',
    unit: '%',
    weight: 1,
    baseline: '98.03',
    target: '98.5',
    remark: '',
  },
  {
    id: '7',
    no: '1.2.2',
    kpi: 'Graduation rate of undergraduate students',
    theme: 'Theme I: Learning-Teaching',
    subTheme: 'Efficiency',
    unit: '%',
    weight: 1,
    baseline: '85',
    target: '90',
    remark: '',
  },
  {
    id: '8',
    no: '2.1.1',
    kpi: 'Number of published research papers in reputable journals',
    theme: 'Theme II: Research & Technology Transfer',
    subTheme: 'Research Output',
    unit: '#',
    weight: 2,
    baseline: '120',
    target: '200',
    remark: '',
  },
  {
    id: '9',
    no: '2.1.2',
    kpi: 'Research funding secured (in millions ETB)',
    theme: 'Theme II: Research & Technology Transfer',
    subTheme: 'Research Output',
    unit: 'M ETB',
    weight: 1.5,
    baseline: '50',
    target: '80',
    remark: '',
  },
  {
    id: '10',
    no: '2.2.1',
    kpi: 'Number of technology transfers to community/industry',
    theme: 'Theme II: Research & Technology Transfer',
    subTheme: 'Technology Transfer',
    unit: '#',
    weight: 1,
    baseline: '5',
    target: '12',
    remark: '',
  },
  {
    id: '11',
    no: '3.1.1',
    kpi: 'Number of community-based projects actively running',
    theme: 'Theme III: Community Engagement',
    subTheme: 'Outreach',
    unit: '#',
    weight: 1,
    baseline: '15',
    target: '25',
    remark: '',
  },
  {
    id: '12',
    no: '3.1.2',
    kpi: 'Number of MoU signed with industries and organizations',
    theme: 'Theme III: Community Engagement',
    subTheme: 'Outreach',
    unit: '#',
    weight: 1,
    baseline: '20',
    target: '35',
    remark: '',
  },
  {
    id: '13',
    no: '4.1.1',
    kpi: 'Staff satisfaction rate',
    theme: 'Theme IV: Good Governance',
    subTheme: 'Institutional Capacity',
    unit: '%',
    weight: 1,
    baseline: '60',
    target: '75',
    remark: '',
  },
  {
    id: '14',
    no: '4.1.2',
    kpi: 'Budget utilization rate',
    theme: 'Theme IV: Good Governance',
    subTheme: 'Institutional Capacity',
    unit: '%',
    weight: 1.5,
    baseline: '82',
    target: '95',
    remark: '',
  },
];

export const vicePresidents = [
  { id: 'academic', label: 'Academic Vice President' },
  { id: 'administrative', label: 'Administrative Vice President' },
  { id: 'research', label: 'Research Vice President' },
];
